---
metadata:
  name: ts-defold
  short_name: ts-defold
  description: "TypeScript <3 Defold"
  language: en
  url: "https://ts-defold.dev"
  sentry: "https://3cd7808a26214f40b3e85e748370cee2@o918528.ingest.sentry.io/5932586"
  pathPrefix: "/"
  siteImage: "/assets/social.png"
  favicon: "/assets/favicon.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/logo.svg"
  logoLink: "/"
  helpUrl: ""
  links:
    - text: Docs
      link: "/"
      external: false
sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/gettingstarted"
      title: ":rocket: Getting Started"
    - order: 2
      path: "/configuration"
      title: ":wrench: Configuration"
    - order: 3
      path: "/editing"
      title: ":writing_hand: Editing Content"
    - order: 4
      path: "/deployment"
      title: ":rocket: Deployment"
    - order: 5
      path: "/developing"
      title: ":computer: Developing"
  links:
    - text: Defold
      link: https://defold.com
    - text: TypeScriptToLua
      link: https://typescripttolua.github.io/
  ignoreIndex: false
pwa:
  enabled: false
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

social:
  discord: https://discord.gg/eukcq5m
  github: https://github.com/ts-defold/create
  twitter: https://twitter.com/tsdefold

features:
  darkMode:
    enabled: false  
    default: false
  editOnRepo:
    location: https://github.com/ts-defold/ts-defold.github.io 
    type: github
    editable: true
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: false
    title: "TS-DEFOLD: TypeScript <3 Defold"
    showIcon: false
    copyright: "2021, Justin Walsh <@thejustinwalsh>"
    webMaster: "Justin Walsh <@thejustinwalsh>"
    managingEditor: "Justin Walsh <@thejustinwalsh>"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "gatsby"
  scrollTop: false
  search:
    enabled: false
    engine: 'localsearch'
    placeholder: 'Search'
    startComponent: 'icon'
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 3
  fullScreenMode: 
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
